Feature/share funct
Plant-for-the-Planet/planet-webapp pull request #171
Opened 2020-09-09 13:45 UTC by nirali25parekh

Changes in this pull request:
- share urls for social media linked
1. email (with subject and body)
2. facebook (with url and caption text)
3. twitter (with tweet text)
4. linkedin (with text)  

![Plant-for-the-Planet - Google Chrome 2020-09-09 18-07-54](https://user-images.githubusercontent.com/53833059/92602765-35516b80-f2cc-11ea-9ac3-3895cc1a2692.gif)

@harshvitra

2020-09-10 15:43 UTC, sagararyal commented
<img width="663" alt="Screen Shot 2020-09-10 at 5 42 09 PM" src="https://user-images.githubusercontent.com/5401575/92756259-f6371f00-f38c-11ea-8acd-9986e83e1ae7.png">


<img width="1440" alt="Screen Shot 2020-09-10 at 5 42 23 PM" src="https://user-images.githubusercontent.com/5401575/92756297-018a4a80-f38d-11ea-97e8-6c036a6acf14.png">

<img width="726" alt="Screen Shot 2020-09-10 at 5 42 49 PM" src="https://user-images.githubusercontent.com/5401575/92756383-136bed80-f38d-11ea-8831-858549e4c2c4.png">
  
<img width="865" alt="Screen Shot 2020-09-10 at 5 43 10 PM" src="https://user-images.githubusercontent.com/5401575/92756434-1ebf1900-f38d-11ea-8fea-6833cafe5189.png">

2020-09-10 15:47 UTC, sagararyal commented
@nirali25parekh please use share buttons like this.
@sarveshpro can help with the font awesome variant of the icons.
<img width="187" alt="Screen Shot 2020-09-10 at 5 45 03 PM" src="https://user-images.githubusercontent.com/5401575/92756756-647be180-f38d-11ea-99a6-e6b5b9c2c226.png">

reference is available at the bottom of this page.
https://xd.adobe.com/view/8f1c5110-4d7d-445d-8283-8eb1674ce2e4-da4f/screen/12e48f82-7be4-4991-906f-7f5fb8b5c7ab

Also please include a download button instead of email: https://fontawesome.com/icons/download?style=regular

use font awesome regular for display and move to font awesome solid icon variant on hover.

2020-09-10 20:19 UTC, felixfinkbeiner commented
<img width="530" alt="Screenshot 2020-09-10 at 15 17 38" src="https://user-images.githubusercontent.com/29404196/92798854-9acc5780-f3b3-11ea-834f-be177816cd34.png">

Let's have this kind of thing where the birds represent (in this order):

- Download
- facebook
- instagram
- twitter
- email

2020-09-10 21:50 UTC, nirali25parekh commented
<br/>
The color changes on hover according to their respective colors. This is how it currently looks

<br/>

![Plant-for-the-Planet - Google Chrome 2020-09-11 03-09-23](https://user-images.githubusercontent.com/53833059/92812541-155d9d00-f3dd-11ea-913b-ab018689bcd5.gif)

<br/>
<br/>

The download button outlined was in the premium package in FontAwesome version, so used solid for both.

<br/>

<img src="https://user-images.githubusercontent.com/53833059/92812674-5950a200-f3dd-11ea-8305-8c52d9307b3a.JPG" height="300px"/>

<br/>

2020-09-11 14:42 UTC, nirali25parekh commented
- the share buttons frontend changes done
- jpeg download functionality is done

![phone_download](https://user-images.githubusercontent.com/53833059/92937874-7e8af200-f469-11ea-812e-2b52be9636da.gif)

2020-09-13 19:55 UTC, sagararyal commented
<img width="373" alt="Screen Shot 2020-09-13 at 9 54 48 PM" src="https://user-images.githubusercontent.com/5401575/93027209-c0ec3480-f60b-11ea-8fba-196825ad8f55.png">

<img width="899" alt="Screen Shot 2020-09-13 at 9 53 32 PM" src="https://user-images.githubusercontent.com/5401575/93027204-b762cc80-f60b-11ea-9dc8-a393a8f59f85.png">

2020-09-13 19:57 UTC, sagararyal commented
Download on Safari 13.1.2 

Bug:
![component-2](https://user-images.githubusercontent.com/5401575/93027241-ec6f1f00-f60b-11ea-8fc4-5442a89fa2f8.jpeg)

<img width="515" alt="Screen Shot 2020-09-13 at 9 56 46 PM" src="https://user-images.githubusercontent.com/5401575/93027271-0e68a180-f60c-11ea-9e9c-5dab34108217.png">
<img width="565" alt="Screen Shot 2020-09-13 at 9 56 41 PM" src="https://user-images.githubusercontent.com/5401575/93027273-1294bf00-f60c-11ea-8915-f8f268058f55.png">
<img width="494" alt="Screen Shot 2020-09-13 at 9 56 38 PM" src="https://user-images.githubusercontent.com/5401575/93027274-17597300-f60c-11ea-9005-8b1158bdd7dd.png">
<img width="505" alt="Screen Shot 2020-09-13 at 9 56 34 PM" src="https://user-images.githubusercontent.com/5401575/93027275-1a546380-f60c-11ea-8258-9244b8cac6c1.png">

2020-09-13 20:04 UTC, sagararyal requested changes

2020-09-13 20:04 UTC, sagararyal commented on src/features/public/Donations/components/ThankYou.tsx
>              <div className={styles.donationTenant}>
plant trees at {{tenantURL}} there is a variable from ENV

2020-09-13 20:04 UTC, sagararyal commented on src/features/public/Donations/components/ShareOptions.jsx
> +    : 'trilliontreecampaign.org';
use {tenantUrl}

2020-09-13 20:04 UTC, sagararyal commented on src/features/public/Donations/components/ShareOptions.jsx
> +        navigator.clipboard.writeText('Dummy text copied to clipboard!');
This needs to be complete.

2020-09-13 20:04 UTC, sagararyal commented on src/features/public/Donations/components/ShareOptions.jsx
> +          <DownloadSolid color="rgba(0,0,0,0.9)" />
change colors to planet grey

2020-09-14 19:32 UTC, nirali25parekh commented
Changes:
- image download bug fixed on safari
- icons change > color, size, round border, layout
- redundant components removed
- env variables used tentantUrl

![shareIcons](https://user-images.githubusercontent.com/53833059/93129678-0fbeca80-f6ef-11ea-8fb4-774cd581598a.JPG)

2020-09-14 21:32 UTC, Plant-for-the-Planet commented
@nirali25parekh 
I still don't see the circles but that is perfectly fine.

- [ ] Need to increase the size/resolution of the downloaded image.

<img width="428" alt="Screen Shot 2020-09-14 at 11 31 34 PM" src="https://user-images.githubusercontent.com/6512255/93140280-74bff380-f6e2-11ea-94f7-cf55f2bf2a9b.png">

2020-09-15 17:28 UTC, nirali25parekh commented
changes:
- safari share links fixed
- file name changed
- image quality (I scaled the image from 1.0 to 5.0, but the downloaded image still seems blur. I'm looking into other ways it can be improved)

2020-09-15 19:23 UTC, felixfinkbeiner commented
1. Please remove the horizontal line that separates the text from the share card

2. When clicking the twitter icon or the email icon on my android it opens the share card instead of twitter even though I have the twitter app installed (same for insta and fb but I don't have those apps)

3. Is there a legal reason we need "pay with Credit Card"? Or what was our motivation for including it. I don't think it's necessary. People know what they paid with and it just makes this text longer (and is grammatically incorrect)

The download works really well. Good job on managing to rename the downloaded file!!!

2020-09-15 19:28 UTC, felixfinkbeiner commented
Oh and a couple more things:

1. In the download the logo and the trillion trees is super low res while the adjusted text looks great. But I think you know that

2. The plant trees at www.trillion does not need "www." And it should be right at the bottom of the card. Ideally, in the card preview it would be a bit further up (as it is now) to make space for the share buttons, but once you actually download it, the text would be further down. Is that possible?

3. In the share page, there is too much space between the bottom of the buttons and the bottom of the pop-up

2020-09-15 20:43 UTC, harshvitra commented
> 3\. Is there a legal reason we need "pay with Credit Card"? Or what was our motivation for including it. I don't think it's necessary. People know what they paid with and it just makes this text longer (and is grammatically incorrect)

For Apple/Google pay we need it 
@sagararyal and I had a conversation on this long back, please confirm

2020-09-15 20:53 UTC, harshvitra commented
**To Do -** 

- [ ] Please remove the horizontal line that separates the text from the share card
 
- [ ] When clicking the twitter icon or the email icon on my android it opens the share card instead of twitter even though I have the twitter app installed (same for insta and fb but I don't have those apps)

- [ ] Is there a legal reason we need "pay with Credit Card"? Or what was our motivation for including it. I don't think it's necessary. People know what they paid with and it just makes this text longer (and is grammatically incorrect) @sagararyal please comment

- [ ] In the download the logo and the trillion trees is super low res while the adjusted text looks great. But I think you know that
 
- [ ] The plant trees at www.trillion does not need "www." And it should be right at the bottom of the card. Ideally, in the card preview it would be a bit further up (as it is now) to make space for the share buttons, but once you actually download it, the text would be further down. Is that possible?
 
- [ ] In the share page, there is too much space between the bottom of the buttons and the bottom of the pop-up

2020-09-15 21:46 UTC, Plant-for-the-Planet commented
Moving remaining tasks to a new issue and merging this to develop.

2020-09-15 21:47 UTC, merged